"""Ports used by application services and implemented by adapters."""

from typing import Protocol


class CheckRepository(Protocol):
    def check_kinds(self): ...
    def get(self, name): ...
    def upsert(self, body): ...
    def list_checks(self): ...


class RunRepository(Protocol):
    def add_run(self, command): ...
    def dashboard(self, limit, workflow): ...
    def last_values(self, workflow): ...
    def count_runs(self): ...


class RunQueue(Protocol):
    def put(self, command): ...
    def get(self): ...
    def task_done(self): ...
    def qsize(self): ...


class EventPublisher(Protocol):
    def publish(self, message): ...
    def subscribe(self): ...
    def unsubscribe(self, subscription): ...


class Clock(Protocol):
    def now_iso(self): ...
